language: node_js
node_js:
- 5
- 4
- 0.12
matrix:
  include:
  - node_js: 6
    env: DEPLOY=true
after_script: if [[ $DEPLOY == "true" ]] ; then ./node_modules/.bin/gulp condensation:deploy
  ; else echo "no deploy" ; fi
env:
  global:
  - secure: hXZT5jE/U6ZqGChV1gY0723cST45z4wUqAwCiWz18akoUk6M7StBwYidhdM0jTHoAuwx2XcRYz4f39ZVXJS1e8LE+VuEsRR95g1yrCYkSaoueuU/z2OWNmPjQGrWNXHsDNr8uE12H4C6VUOXS2ldgAkvb8IhM1FC4gplZi8dHfYqaZv1E8YkTeQn2RyWMB9fk5GKACF7RqtN8EOtf3aBFk3lFpDUpRtOqw6InufCkA6d+lfU2xJT3Xei/JNBE1RGRy8Z/gSYdIY+W1RBiug2jLVD02bhRqxUXEmoTY2nTx36o6kivfKBcQDhWHQVamcti6332H41fx4y+KQNhziRdo5C/YybzjWXRgAbPfnVJQprLx4hjWVeCWTIDkmuyDqlKwSnsZKqeU4W5D6bcZW9OPxOucJrvQtVzcsTPgaMe2GAv0l59pIvMRS8vzUMZkcssVySspDFQ49o7nLEz3TKdZz4dMDbwkBsY6PO6m0GR6zDLc1KOA+Vvq73KzX0uOMgHaaSsLSjBeuX6n/KDAsh06P0iuVQ5oGxIdEqkyVrDkdZre3DUzFFvjUeKTWa5ejUAJ49QuHSJZgnJdQHVuvHnl/vuy4qmBgLay/fyHfZBIb4lG0KzxNiGerXTyHgsHhnu1Mx7OzQ8HW4a3tNhaBCFJoaIa7tqalZaUAGxG5T6cA=
  - secure: Gb6NkMb4ut6r03uQW7MQS63ncH1loq5cC1CgaVBhlfNFmhmLpczmGY/mdXJzm9vLA9GghutfkJJnbee+AYb7r+USqGHG/A0ytI2Yhwv3eDkwYlSAhgWad00GGriFFpaJL9RgC6ukS6tkPJ0bfhyWkQiYx3ffDtFvqd93btSHZNi1J41COjIHY4vexB8SvimIQ+cxClUSudwj0NMZDLP6ouizxt50/UsSu5ypzvGYNxa7vE/ZW/A1aJU54rIZNAJ3xGt7jGTKaxsUL3/R1sbg92TKmONBuC4/rrDFjY/7etdCt+jpb9+34m8M1MhYpgS1HM5Y9TZmOMT28aPrVNRdqPuLLKPKu6zGR7ITJ6f9FWEjDFdT+aXWqG+q5/dA+r1kADrrw8hNPauNv2ZSpQijAS79zJZmPYBjkdc5adZASTcwKsBJQtFbt2bmeeAxF8qrWeDWQtgVnOBo5WW8+K8z3J2erwwGv0QyDcLqvdN1zkA36mVZXmy5B+su7jOx4YU9fRlkOTWF7KByMzYZktLCOjSJesoSu09yfvM6j/l/OPFu9dmS9gomDvG2gi5FG3AgzV4LjfZ7w8nn1VXcktn+85O9geCEQi0X3LJgUOBRuZKxz7p5rkWRejNNz/zZNtxGRHVm3W1fg6v+2bYKD1VwAsNZVQ5ALdEgcR1iK/FJbhI=
